// Regenerate with: bun scripts/generate-icons.tsx
// Use the same Phosphor Notebook SVG as the sidebar brand.
import { mkdir, readFile, writeFile } from "node:fs/promises"
import { renderToStaticMarkup } from "react-dom/server"
import { NotebookIcon } from "@phosphor-icons/react/dist/ssr"
import sharp from "sharp"

const root = new URL("../", import.meta.url)
const license = await readFile(
  new URL("node_modules/@phosphor-icons/react/LICENSE", root),
  "utf8"
)
const notice = `Phosphor Notebook icon (regular weight)\nhttps://github.com/phosphor-icons/react\n\n${license}`
await mkdir(new URL("public/icons/", root), { recursive: true })
await writeFile(new URL("public/icons/LICENSE.txt", root), notice)

function iconSvg({ rounded = false, maskable = false } = {}) {
  const inset = maskable ? -48 : 0
  const extent = maskable ? 352 : 256
  return renderToStaticMarkup(
    <NotebookIcon
      size={256}
      weight="regular"
      color="#efeff0"
      viewBox={`${inset} ${inset} ${extent} ${extent}`}
    >
      <rect
        x={inset}
        y={inset}
        width={extent}
        height={extent}
        rx={rounded ? 48 : 0}
        fill="#191a1d"
      />
    </NotebookIcon>
  )
}

const favicon = iconSvg({ rounded: true })
await writeFile(
  new URL("app/icon.svg", root),
  `<!-- Generated by scripts/generate-icons.tsx\n${notice}-->\n${favicon}\n`
)

for (const [path, size, maskable] of [
  ["app/apple-icon.png", 180, false],
  ["public/icons/icon-192.png", 192, false],
  ["public/icons/icon-512.png", 512, false],
  ["public/icons/icon-maskable-512.png", 512, true],
] as const) {
  await sharp(Buffer.from(iconSvg({ maskable })))
    .resize(size, size)
    .png()
    .toFile(new URL(path, root).pathname)
}

// ICO supports PNG entries; keep 16, 32, and 48px images for browser/OS fallbacks.
const sizes = [16, 32, 48]
const images = await Promise.all(
  sizes.map((size) =>
    sharp(Buffer.from(favicon)).resize(size, size).png().toBuffer()
  )
)
const header = Buffer.alloc(6 + 16 * sizes.length)
header.writeUInt16LE(1, 2)
header.writeUInt16LE(sizes.length, 4)
let offset = header.length
for (const [index, data] of images.entries()) {
  const entry = 6 + 16 * index
  header[entry] = sizes[index]
  header[entry + 1] = sizes[index]
  header.writeUInt16LE(1, entry + 4)
  header.writeUInt16LE(32, entry + 6)
  header.writeUInt32LE(data.length, entry + 8)
  header.writeUInt32LE(offset, entry + 12)
  offset += data.length
}
await writeFile(
  new URL("app/favicon.ico", root),
  Buffer.concat([header, ...images])
)
console.log("Generated SVG, ICO, Apple touch, and PWA icons.")
